baseURL: 'http://hoanghapham.github.io/'
languageCode: 'en-us'
title: "Ha Pham"
theme: "PaperMod"

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 5
    ordered: false

params:

  # Papermod params
  homeInfoParams:
    Title: Ha Pham
    Content: Aspiring Machine Learning Engineer

  socialIcons: # optional
    - name: LinkedIn
      url: https://www.linkedin.com/in/hoanghapham/
    - name: GitHub
      url: https://github.com/hoanghapham
    - name: Youtube
      url: https://www.youtube.com/@BlacK201100
    - name: CV
      url: /files/Pham-Hoang-Ha_CV.pdf

  profileMode:
    enabled: True
    title: Ha Pham
    subtitle: Aspiring Machine Learning Engineer
    imageUrl: "about/ava.png" 
    imageTitle: "avatar"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: About Me
        url: /about
      - name: Portfolio
        url: /projects
      - name: Blog
        url: /posts

  # showShareButtons: true
  showReadingTime: true
  showBreadCrumbs: true
  showCodeCopyButtons: true
  comments: false

  # Site params
  author: Ha Pham

  assets:
    enableFontAwesome: true

menu:
  main:
    - identifier: about
      name: About Me
      url: /about
      weight: 1
    - identifier: portfolio
      name: Portfolio
      url: /projects
      weight: 2
    - identifier: blog
      name: Blog
      url: /posts
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

# module:
#   imports:
#     path: github.com/zetxek/adritian-free-hugo-theme